version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: unless-stopped
    expose:
     - "9200"
     - "9300"
    environment:
     - cluster.name=elasticsearch
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  zk:
    image: zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    expose:
     - "2181"
    environment:
     - ZOO_MY_ID=3
  cimi:
    image: nuvla/cimi-container:latest
    container_name: cimi
    restart: unless-stopped
    ports:
     - "8201:8201"
    environment:
     - ZK_ENDPOINTS="zk:2181"
     - ES_HOST=es
     - ES_PORT=9300

